### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by thijstakken**
You have to run the server component instead of the client. prutser @lukasvdberk

### CODE REVIEW

**Comment by lukasvdberk** [comment]
no @thijstakken

**Comment by lukasvdberk** [comment]
idk about who added the Dockerfile but that guy is a idiot

**Comment by lukasvdberk** [comment]
were are the terraform scripts?

**Comment by sonofice** [comment]
No terraform @lukasvdberk

**Comment by thijstakken** [comment]
how to run on rasperriy pie

**Pull request closed without merging**
